import React from 'react'

export default function About() {
  return (
    <div className='flex flex-col justify-center items-center'>
      <h1 className='text-slate-800 dark:text-white text-6xl'> Text Utiliy Made By Ajay Singh</h1>
      <p className='text-slate-900 dark:text-white px-20 py-10'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatum consectetur qui ipsam sit iste illo ea ab quisquam doloremque vitae eveniet, laboriosam, atque ratione fuga ipsa consequuntur nulla similique itaque. Expedita error natus illo. Fugit, earum quisquam pariatur alias quia vel iste impedit necessitatibus inventore perspiciatis praesentium explicabo, provident perferendis temporibus sapiente, doloribus dolorem veniam aut velit eius! In dolorem quidem quam sit quibusdam aliquam explicabo eius id maxime quae fugiat culpa tempora neque magnam similique, modi harum voluptatum possimus ad unde, amet soluta rem praesentium? Perspiciatis veritatis sapiente dolorum maxime, ad dolores, assumenda obcaecati quisquam nihil deleniti vel natus voluptas debitis eligendi cupiditate voluptatibus vero ut? Voluptatibus neque quaerat impedit, consequuntur vitae atque iste cupiditate unde voluptate consectetur repellendus accusamus velit provident fugiat magnam asperiores recusandae quod nobis natus possimus expedita corporis doloribus! Architecto fugit fuga incidunt quos! Dolorum optio corrupti omnis enim culpa accusamus, blanditiis sed tenetur? Deserunt sint, omnis voluptates nesciunt numquam adipisci quisquam veritatis labore alias doloribus nostrum cumque quidem a iure natus praesentium, obcaecati itaque? Laborum laudantium sequi, ratione tempore, quis ad magni ex, facilis voluptate impedit quaerat asperiores nulla? Voluptatum inventore nulla voluptates error! Dolorum, consequuntur rerum quis blanditiis ut explicabo sapiente animi soluta ipsam laudantium tempore quia fugit ea! Magni, quidem adipisci magnam perspiciatis voluptatem qui nisi minus fuga neque, quibusdam aut consectetur mollitia molestias eum! Explicabo quos at ullam autem perspiciatis quidem illum. Tempore iusto quo eos vel. Dolor eveniet eius cupiditate maxime alias pariatur voluptas magni consequatur quibusdam explicabo, sed labore quam numquam? Ipsum delectus quos vero ex dignissimos sunt incidunt, libero officiis laudantium quaerat, animi nam doloribus ea unde rerum quo. Numquam tenetur totam sequi accusantium libero, dicta voluptates sit odio! Dolore, explicabo. Accusantium itaque possimus sapiente aperiam autem dignissimos voluptatem nisi excepturi, alias, velit maxime, perferendis debitis dicta at.</p>
    </div>
  )
}
